version: '2.3'
services:
  notebook:
    build: .
    env_file: .env
    ports:
      - "5003:8888"
    volumes:
      - ../data:/data
      #- /mnt/qb/data:/data
      - /tmp:/tmp
      - .:/src/nnfabrik
      - ./notebooks:/notebooks
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=0
  server_develop:
    build: ..
    ports:
      - "8888:8888"
    volumes:
      - ../../../var/lib/nova/sinz-shared/monkey/toliaslab:/monkeydata
      - ../../../var/lib/nova/sinz-shared:/data
      - ../../../var/lib/nova/sinz-shared/mouse/static:/mousedata
      - ../projects:/notebooks
    env_file: .env
    environment:
      - DISPLAY=$DISPLAY
    runtime: nvidia
